### ISSUE TITLE
[Documentation]: Password limitation | Max 18 characters.

### ISSUE THREAD

**Issue by LilTrublMakr** [jjjonesjr33/petlibro#16]
### What happened ?

I made a separate account as suggested in the readme that is for HA and shared my device to that account. When attempting to log in to the 2nd account, I get a generic error. 

I do use a password manager to generate passwords and the password I am using is 25 characters long with A-Z, a-z, 0-9, !@#$%^* in it. I have not tried a simpler password but will if needed.

### Relevant log output

```python
Logger: custom_components.petlibro.config_flow
Source: custom_components/petlibro/config_flow.py:125
integration: PETLIBRO (documentation)
First occurred: 11:16:41 PM (1 occurrences)
Last logged: 11:16:41 PM

Unexpected exception during validation: Login attempt failed: Code: 1102, Message: ILLEGAL_PASSWORD
Traceback (most recent call last):
  File "/config/custom_components/petlibro/api.py", line 206, in login
    data = await self.session.request("POST", "/member/auth/login", json={
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/petlibro/api.py", line 106, in request
    raise PetLibroAPIError(f"Code: {data.get('code')}, Message: {data.get('msg')}")
custom_components.petlibro.exceptions.PetLibroAPIError: Code: 1102, Message: ILLEGAL_PASSWORD

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/petlibro/config_flow.py", line 125, in _validate_input
    self.token = await api.login(self.email, self.password)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/petlibro/api.py", line 229, in login
    raise PetLibroAPIError(f"Login attempt failed: {e}")
custom_components.petlibro.exceptions.PetLibroAPIError: Login attempt failed: Code: 1102, Message: ILLEGAL_PASSWORD
```

**Comment by jjjonesjr33** [comment]
@LilTrublMakr I'll have to take a look and see if there is a limit on the password complexity or if it's an issue on how the password is encoded and then handed off. As for now, try a simpler password and let me know how it goes.

**Comment by LilTrublMakr** [comment]
Dropped it down to 15 chars with the same char set and it let me log in. When I try to increase the count, it logs me out when I go to set a new one so my guess is that they have it rate limited somehow. I will try 18 and 21 chars later since those are pretty char limit caps.

**Comment by LilTrublMakr** [comment]
Seems like 18 is the magic number!

**Comment by jjjonesjr33** [comment]
Well that's some good news 😄 I'll have to put that info in the wiki. 

Is that also while using a complex password or a simpler one?

**Comment by LilTrublMakr** [comment]
Still a complex password.
