### ISSUE TITLE
[Feature Request]: Display metric/imperial units based on device settings

### ISSUE THREAD

**Issue by quoka12** [jjjonesjr33/petlibro#17]
### Device model name

Granary Smart Camera Feeder

### Device model number

PLAF203

### Device type

Feeder

### Feature name

Today Feeding Quantity

### Describe the feature

First off, thanks a bunch for this awesome integration, it works (almost) flawlessly out-of-the-box for my PLAF203! 

I have my device set to use metric units (grams, milliliters) in the Petlibro app. However, the entity for Today's Feeding Quantity shows the output always in cups - would like to have it in grams. 

Looking at the sensor.py script, it looks like this is hardcoded - note thought that I literally have zero coding knowledge. It would be great if cups/grams could be automatically set based on device settings.

        # Handle today_feeding_quantity as raw numeric value, converting to cups
        elif sensor_key == "today_feeding_quantity":
            feeding_quantity = getattr(self.device, sensor_key, 0)
            # Convert feeding_quantity to cups, where 1/12 cup = 20 ml
            cups = feeding_quantity * (1 / 12)  # Since each 1 unit is 1/12 of a cup
            return f"{round(cups, 2)}"

    @property
    def native_unit_of_measurement(self) -> str | None:
        """Return the native unit of measurement to use in the frontend, if any."""
        # For today_feeding_quantity, display as cups in the frontend
        if self.entity_description.key == "today_feeding_quantity":
            return "cups"
        # For weight, display as ounces in the frontend
        elif self.entity_description.key == "weight":
            return "oz"

        # Default behavior for other sensors
        return self.entity_description.native_unit_of_measurement_fn(self.device)

### What problem does this feature solve?

Displays unit of today's feeding quantity based on device settings

### Available to help with the feature development

- [X] I agree to help with testing or providing relevant information for this feature request

**Comment by jjjonesjr33** [comment]
@quoka12 this is a dupe issue/request that we looking to resolve from #8 The goal is to be able to give the option to set what you want so you can match it to what the actual app is showing/or be able to just control that setting entirely from within home assistant. 

We'll eventually get to the point to were we can do that, but it's based on what petlibro's api allows up to do at the moment.

If you have any more suggestions or comments, please feel free to let us devs know.
