### ISSUE TITLE
[Device]: PETLIBRO Air Smart Feeder (PLAF108) 

### ISSUE THREAD

**Issue by martinendres** [jjjonesjr33/petlibro#18]
### Device model name

Air Smart Feeder

### Device model number

PLAF108

### Device type

Feeder

### What state, statistic or control do you want to be reported in the integration ?

It would be great if the following PETLIBRO feeder could be integrated. 

https://petlibro.com/products/air-wifi-feeder

What state, statistic or control do you want to be reported in the integration ?
- Schedule feeding
- Staus information in general (battery, filling level, last feeding)
- start manuell feeding

### Available to help integrate the new device

- [X] I agree to help with the integration of the new device by providing the necessary information that will be requested

**Comment by jjjonesjr33** [comment]
@martinendres would you be able to provide information on what the api pulls or give temporary `shared` access to this device via my support account? If you okay with temporary `shared` access, I have a test account setup via `support@jonesinc.dev` that you can give access to via the Petlibro app on your phone. Please let me know when you do as there is a 30 min window for me to accept the device.

**Comment by jjjonesjr33** [comment]
@bhaggs it looks like you were trying to request the same device in https://github.com/jjjonesjr33/petlibro/issues/19 Same request goes out to you as well. Let me know if you can assist in any way.

**Comment by jjjonesjr33** [comment]
Hey @martinendres no need to share, @bhaggs already reached out to me. I'll be looking into it sometime this coming Monday to see what I can get setup. Look for a release once I'm done.

**Comment by itsthekayl** [comment]
I've also got a PLAF108, let me know if you need anything

**Comment by jjjonesjr33** [comment]
This has now been completed in [v1.0.11](https://github.com/jjjonesjr33/petlibro/releases/tag/v1.0.11) 

Let me know if anyone of you have issues @martinendres @itsthekayl @bhaggs

## NOTICE: Home Assistant Fronted Version 20241106.2
____
* There seems to be a delay issue with showing the sensors in Home Assistant fronted version 20241106.2. Please allow the plugin to gather stats from the API to correctly load. This process may take between 5-10 mins. If you still have an issue please report it in bug reports.

  - What I have noticed at first, when the plugin loads, it just shows the sensors as off. Once it does load everything, it all goes back to showing their correct status. Seems to be a bug with fronted version for binary sensors and native unit of measurements.

* Home Assistant Fronted Version 20241106.0 still works as intend and loads the data within the normal 1-2 min time frame.

## What's Changed
* Add support for PetLibro Air Smart Feeder (PLAF108 ) in https://github.com/jjjonesjr33/petlibro/commit/f2864b0172a66b7095d0638dfe43d74644a215ec

![image](https://github.com/user-attachments/assets/5a4752b9-fcf0-426a-90cb-0b6ea2f5c5c1)

## New Contributors
* @bhaggs supported by providing access to their device for implementation on https://github.com/jjjonesjr33/petlibro/issues/18 - PLAF108 / Air Smart Feeder

**Full Changelog**: https://github.com/jjjonesjr33/petlibro/compare/v1.0.10...v1.0.11

**Comment by itsthekayl** [comment]
@jjjonesjr33 The only issue I see is this feeder dispenses in 1/24 cups instead of 1/12. So the feeding amount calculations are doubled.

**Comment by jjjonesjr33** [comment]
Re-opened to fix issue with cups. thanks for letting me know @itsthekayl

**Comment by Nistp** [comment]
@jjjonesjr33 I could submit a PR for that? It seems all I have to do is change 12 to 24, no?

**Comment by jjjonesjr33** [comment]
@Nistp on this one, for a fix we would need to update the `today_feeding_quantity` in the `sensor.py` for example

```python
        # Handle today_feeding_quantity as raw numeric value, converting to cups
        elif sensor_key == "today_feeding_quantity":
            feeding_quantity = getattr(self.device, sensor_key, 0)
            # Determine the conversion factor based on device-specific attributes or context
            conversion_factor = 1 / 12  # Default conversion factor
            if hasattr(self.device, "conversion_mode") and self.device.conversion_mode == "1/24":
                conversion_factor = 1 / 24
            
            cups = feeding_quantity * conversion_factor
            return f"{round(cups, 2)}"
```
and here
```python
        PetLibroSensorEntityDescription[AirSmartFeeder](
            key="today_feeding_quantity",
            translation_key="today_feeding_quantity",
            icon="mdi:scale",
            native_unit_of_measurement_fn=unit_of_measurement_feeder,
            device_class_fn=device_class_feeder,
            state_class=SensorStateClass.TOTAL_INCREASING,
            name="Today Feeding Quantity"
        ),
```
then we need to update the class to
```python
class AirSmartFeeder(Device):  # Inherit directly from Device
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Set default conversion mode for AirSmartFeeder
        self.conversion_mode = "1/24"  # AirSmartFeeder uses 1/24 cup conversion

    async def refresh(self):
        """Refresh the device data from the API."""
        try:
            await super().refresh()  # Call the refresh method from Device
            
            # Fetch specific data for this device
            grain_status = await self.api.device_grain_status(self.serial)
            real_info = await self.api.device_real_info(self.serial)
            
            # Dynamically update conversion mode if needed
            if "conversionMode" in real_info:  # Example: real_info provides conversionMode
                self.conversion_mode = real_info["conversionMode"]

            # Update internal data with fetched API data
            self.update_data({
                "grainStatus": grain_status or {},
                "realInfo": real_info or {}
            })
        except PetLibroAPIError as err:
            _LOGGER.error(f"Error refreshing data for AirSmartFeeder: {err}")

```

I was planning to do a test with this, but I've been a bit busy lately. Although I am not sure if it will interfere with the other devices yet...

**Comment by Nistp** [comment]
@jjjonesjr33 I assume here I was meant to add a "conversion_mode" attribute? Like so?

```python

           PetLibroSensorEntityDescription[AirSmartFeeder](
            key="today_feeding_quantity",
            translation_key="today_feeding_quantity",
            icon="mdi:scale",
            native_unit_of_measurement_fn=unit_of_measurement_feeder,
            device_class_fn=device_class_feeder,
            state_class=SensorStateClass.TOTAL_INCREASING,
            name="Today Feeding Quantity",
            conversion_mode = None
        ),
```

But yeah, with and without, I've tried a quick test and no luck, it still displayed the wrong amount (using 1/12, not 1/24). I'll poke more at this over the rest of this week.

**Comment by Nistp** [comment]
@jjjonesjr33 alright, I'm not sure what I did wrong, but yes, the code you've provided works! Sadly, I only have the Air Feeder so I can't really test against other feeders. Do you still want me to submit a PR or what should I do?

**Comment by jjjonesjr33** [comment]
@Nistp yea, go ahead and submit a PR for the update.
