### ISSUE TITLE
[Device]: Air Smart Feeder

### ISSUE THREAD

**Issue by bhaggs** [jjjonesjr33/petlibro#19]
### Device model name

Air Smart Feeder

### Device model number

PLAF108

### Device type

Feeder

### What state, statistic or control do you want to be reported in the integration ?

Essentially the majority of the sensors used for the Granary Smart Feeder, with a few exceptions for features not included in the Air Smart Feeder like the desiccant sensor.  

### Available to help integrate the new device

- [X] I agree to help with the integration of the new device by providing the necessary information that will be requested

**Comment by bhaggs** [comment]
Closing as dupe, as looks like someone else opened a request just a little before me for the same model. #18 

Will follow that issue and happy to test as needed.

**Comment by jjjonesjr33** [comment]
This is a dupe of https://github.com/jjjonesjr33/petlibro/issues/18
