### ISSUE TITLE
[Feature Request]: Reset Dessicant Reminder

### ISSUE THREAD

**Issue by C4-Dimitri** [jjjonesjr33/petlibro#24]
### Device model name

I think all feeder models?

### Device model number

I think all feeder models?

### Device type

Feeder

### Feature name

Reset Dessicant Reminder

### Describe the feature

Ability to reset (and potentially set the timeout as well?) for the dessicant reminder:

API endpoint:
https://api.us.petlibro.com/device/device/desiccantReset

post request data:
```
{
  "deviceSn": "AF06013AF056214A2",
  "requestId": "2089bebb53034ef0ae04ee1bb3b3aa55",
  "timeout": 5000
}
```

response data:
```
{
  "code": 0,
  "msg": null,
  "data": null
}
```

the frequency seems to be set seperately in this endpoint:
https://api.us.petlibro.com/device/device/maintenanceFrequencySetting

post request data:
```
{
  "deviceSn": "AF06013AF056214A2",
  "key": "DESICCANT",
  "frequency": 60,
  "requestId": "6ede2055ec5344beba5fbb3755b63c5a",
  "timeout": 5000
}
```

response data:
```
{
  "code": 0,
  "msg": null,
  "data": null
}
```
### What problem does this feature solve?

More control from homeassistant rather than app.

### Available to help with the feature development

- [X] I agree to help with testing or providing relevant information for this feature request

**Comment by jjjonesjr33** [comment]
Actually the air feeder I got added the other day doesn't have this on the physical device or in the app. However when I have it loaded in the api it does show a default of 14 days. 

I'm not sure though if the days count down? That might be something for us to investigate.

**Comment by jjjonesjr33** [comment]
Having the ability to reset it from HA would be great. Also being able to control the days, even if it's a once set and forget setting, would be worth it as well.

**Comment by brwyatt** [comment]
I assume this is the issue to follow for the PLWF105 cleaning/filter reset as well? (I don't see anything specific to that, but see it noted in the README as WIP/planned)

**Comment by jjjonesjr33** [comment]
@brwyatt yeah, they all should be similar code wise for this bit. At least to what I have gathered from the API.

**Comment by C4-Dimitri** [comment]
@brwyatt @jjjonesjr33, pull request created - should hopefully be implemented well. we may need to change a bit in the number.py to have both sound level and dessicant replacement frequency work at the same time. i think it might be ok, but worth checking.
