### ISSUE TITLE
[Feature Request]: Enable/Disable Sound For OneRFIDFeeder (maybe others too).

### ISSUE THREAD

**Issue by C4-Dimitri** [jjjonesjr33/petlibro#27]
### Device model name

OneRFIDFeeder

### Device model number

PLAF301

### Device type

Feeder

### Feature name

Enable/Disable Sound on Feeder

### Describe the feature

Enable/Disable Sound on Feeder

https://api.us.petlibro.com/device/setting/updateSoundSetting
Post: Disable Sound:
```
{
  "deviceSn": "AF06013AF056214A2",
  "soundSwitch": false,
  "soundAgingType": 1,
  "soundStartTime": null,
  "soundEndTime": null
}
```
Post: Enable Sound:
```
{
  "deviceSn": "AF06013AF056214A2",
  "soundSwitch": true,
  "soundAgingType": 1,
  "soundStartTime": null,
  "soundEndTime": null
}
```
Post: set specific times sound is enabled:
```
{
  "deviceSn": "AF06013AF056214A2",
  "soundSwitch": true,
  "soundAgingType": 2,
  "soundStartTime": "01:00",
  "soundEndTime": "18:00"
}
```
So the soundAgingType needs to be set to 2, to allow for custom times to be sent, and then set the start & end times.

change volume:
https://api.us.petlibro.com/device/setting/updateVolumeSetting
Post: set volume to specific amount 1 - 100:
```
{
  "deviceSn": "AF06013AF056214A2",
  "volume": 66
}
```

### What problem does this feature solve?

Ability to turn sound on and off.

### Available to help with the feature development

- [X] I agree to help with testing or providing relevant information for this feature request

**Comment by jjjonesjr33** [comment]
Completed in pull https://github.com/jjjonesjr33/petlibro/pull/23
