### ISSUE TITLE
[Bug]: Unexpected exception during validation: Login attempt failed: Code: 1101, Message: MEMBER_NOT_EXIST

### ISSUE THREAD

**Issue by bredmor** [jjjonesjr33/petlibro#32]
### What happened ?

During initial configuration, I enter the username and password I created for a new account that has been added to my home through the Petlibro LITE app. I've verified the credentials are correct and have used them to log in to the app on 2 different mobile devices.

When I click "Submit", I receive this UI error, 
![image](https://github.com/user-attachments/assets/3f3567d4-1557-4f2e-bd4b-411eca477dca)
and the included log output.

### Relevant log output

```python
Traceback (most recent call last):
  File "/config/custom_components/petlibro/api.py", line 206, in login
    data = await self.session.request("POST", "/member/auth/login", json={
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/petlibro/api.py", line 106, in request
    raise PetLibroAPIError(f"Code: {data.get('code')}, Message: {data.get('msg')}")
custom_components.petlibro.exceptions.PetLibroAPIError: Code: 1101, Message: MEMBER_NOT_EXIST

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/petlibro/config_flow.py", line 125, in _validate_input
    self.token = await api.login(self.email, self.password)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/petlibro/api.py", line 229, in login
    raise PetLibroAPIError(f"Login attempt failed: {e}")
custom_components.petlibro.exceptions.PetLibroAPIError: Login attempt failed: Code: 1101, Message: MEMBER_NOT_EXIST
```

**Comment by jjjonesjr33** [comment]
@bredmor the key thing you pointed out is you are using the "Petlibro LITE" app. That does not work with this integration, the device that you have needs to be able to function with the "Petlibro" app.

**Comment by bredmor** [comment]
Your README says that this project supports the PLAF103 feeders, but the PLAF103 feeders I own only work with the Petlibro LITE app and do not pair to the full Petlibro app.

Is there a specific model or firmware version that allowed the use of that model with the other app?

**Comment by jjjonesjr33** [comment]
Can confirm there is two versions @bredmor 

	1.	PLAF103 Version 1: This version uses the “Petlibro Lite” app, which is based on the Tuya platform. It allows integration with services like Alexa and Home Assistant. ￼
	2.	PLAF103 Version 2: This newer version operates with the “Petlibro” app and does not utilize the Tuya platform, limiting integration with other smart home services. ￼

To determine which version you have, check the QR code on your product or manual; scanning it should direct you to the appropriate app. ￼

**Comment by bredmor** [comment]
That explains it, I have the version that runs on the Tuya platform. Apparently there is no way to determine which you will get, you just have to hope you get the right one. I have briefly looked into it today and seen reports of people ordering 2 feeders and getting one of each!

Frustrating, but thank you for helping me figure out why this wasn't working.
