### ISSUE TITLE
[Bug]: Can only login on 1 instance

### ISSUE THREAD

**Issue by ITensEI** [jjjonesjr33/petlibro#39]
### What happened ?

When I first set up the account I used Google to login setting my region to Canada. Then once i found this integration and saw that it only supports US. I deleted my account and created a new one in the US with email/pwd. Using that I was able to login and the integration did pull data. 

Then I noticed that it kept logging me out of the app and saw HA logs showing:
`NOT_YET_LOGIN error occurred for https://api.us.petlibro.com/device/device/baseInfo. Trying re-login.`
So I can either be signed in on the app or using the integration it seems.

I can't find their API docs so it could be a limitation on their end, but please check if there's a way to enable multiple sessions on your end.

I'm not sure what model the feeder is as I can't find it on the website, but this is the one I got:
[PETLIBRO Automatic Cat Feeder Wet Food Dispenser Refrigerated](https://www.amazon.ca/dp/B0DCG53ZL4)

Also, the integration didn't add any actions. Not sure if it's cuz this model is not supported fully yet. The temperature is also in Fahrenheit, probably cuz US server, but if it can be converted to Celsius (maybe with a setting) that'd be awesome!

I added all the log messages from my set up. Willing to test and debug things if needed.

### Relevant log output

```python
This error originated from a custom integration.

Logger: custom_components.petlibro.number
Source: custom_components/petlibro/number.py:146
integration: PETLIBRO (documentation)
First occurred: 20:51:59 (2 occurrences)
Last logged: 21:35:51

No number entities added, entities list is empty!

--------------------------------------------------------------

This error originated from a custom integration.

Logger: custom_components.petlibro.button
Source: custom_components/petlibro/button.py:233
integration: PETLIBRO (documentation)
First occurred: 20:51:59 (2 occurrences)
Last logged: 21:35:51

No buttons added, entities list is empty!

--------------------------------------------------------------

This error originated from a custom integration.

Logger: custom_components.petlibro.switch
Source: custom_components/petlibro/switch.py:121
integration: PETLIBRO (documentation)
First occurred: 20:51:59 (2 occurrences)
Last logged: 21:35:51

No switches added, entities list is empty!

--------------------------------------------------------------

This error originated from a custom integration.

Logger: custom_components.petlibro.api
Source: custom_components/petlibro/api.py:94
integration: PETLIBRO (documentation)
First occurred: 20:55:01 (7 occurrences)
Last logged: 21:35:51

NOT_YET_LOGIN error occurred for https://api.us.petlibro.com/device/device/baseInfo. Trying re-login.
NOT_YET_LOGIN error occurred for https://api.us.petlibro.com/device/device/list. Trying re-login.

--------------------------------------------------------------

Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:599
integration: Sensor (documentation, issues)
First occurred: 20:51:59 (1 occurrences)
Last logged: 20:51:59

Error adding entity None for domain sensor with platform petlibro
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 599, in _async_add_entities
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 826, in _async_add_entity
    original_icon=entity.icon,
                  ^^^^^^^^^^^
  File "/config/custom_components/petlibro/sensor.py", line 144, in icon
    if (icon := self.entity_description.icon_fn(self.state)) is not None:
                                                ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 544, in state
    value = self.native_value
            ^^^^^^^^^^^^^^^^^
  File "/config/custom_components/petlibro/sensor.py", line 133, in native_value
    val = getattr(self.device, sensor_key, None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/petlibro/devices/feeders/polar_wet_food_feeder.py", line 105, in next_feeding_end_time
    time_obj = datetime.strptime(raw_time, "%H:%M")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: strptime() argument 1 must be str, not None

--------------------------------------------------------------

Logger: homeassistant.components.number
Source: components/number/__init__.py:223
integration: Number (documentation, issues)
First occurred: 20:51:59 (1 occurrences)
Last logged: 20:51:59

custom_components.petlibro.number::PetLibroNumberEntity is overriding deprecated methods on an instance of NumberEntity, this is not valid and will be unsupported from Home Assistant 2022.10. Please report it to the custom integration author
```

**Comment by jjjonesjr33** [comment]
@ITensEI please refer to the wiki on [PetLibro Account Management](https://github.com/jjjonesjr33/petlibro/wiki/PetLibro-Account-Management) for account management. You have to have a 2nd account that has access to the device by using the shared method listed in the wiki.

Also the model you are referring to from amazon should be "Polar Wet Food Feeder (PLAF109)" please double check the device make/model/version and report back to me what it is. There may be an instance where there is a slightly different model/version that we need to account for.

For the Fahrenheit, to be converted to Celsius, please put in a feature request for that.

Let me know if you if you have any other problems or if you have any other questions.

**Comment by jjjonesjr33** [comment]
@ITensEI, based on my last comment, I’ll be closing this issue for now. If you need further assistance or encounter additional problems, please don’t hesitate to reopen the issue or reach out. Thank you!
