### ISSUE TITLE
[Bug]: Unable to log into integration

### ISSUE THREAD

**Issue by patti0176** [jjjonesjr33/petlibro#40]
### What happened ?

I'm unable to log into the integration using either my primary account or a newly created service account. I've followed the password requirements wiki and am using a password with less than 18 character and no symbols.

### Relevant log output

```python
Logger: custom_components.petlibro.config_flow
Source: custom_components/petlibro/config_flow.py:125
integration: PETLIBRO (documentation)
First occurred: 12:13:26 PM (3 occurrences)
Last logged: 12:27:47 PM

Unexpected exception during validation: Login attempt failed: Code: 1102, Message: ILLEGAL_PASSWORD
Unexpected exception during validation: Login attempt failed: Code: 1101, Message: MEMBER_NOT_EXIST
Traceback (most recent call last):
  File "/config/custom_components/petlibro/api.py", line 207, in login
    data = await self.session.request("POST", "/member/auth/login", json={
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/petlibro/api.py", line 107, in request
    raise PetLibroAPIError(f"Code: {data.get('code')}, Message: {data.get('msg')}")
custom_components.petlibro.exceptions.PetLibroAPIError: Code: 1102, Message: ILLEGAL_PASSWORD

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/petlibro/config_flow.py", line 125, in _validate_input
    self.token = await api.login(self.email, self.password)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/petlibro/api.py", line 230, in login
    raise PetLibroAPIError(f"Login attempt failed: {e}")
custom_components.petlibro.exceptions.PetLibroAPIError: Login attempt failed: Code: 1102, Message: ILLEGAL_PASSWORD
```

**Comment by jjjonesjr33** [comment]
@patti0176 

I noticed sometime this morning there was an issue going on with their services/app to where I wasn't able to log on as well. It looks like the service has been restored. You might want to try to log into both accounts via the app just to make sure you can log on. 

Also just to confirm are you using a US account?

**Comment by patti0176** [comment]
Both accounts are US accounts and work in the app to initiate a feeding. Logging in today I am seeing the error Login failed: Code: 1101, Message: MEMBER_NOT_EXIST with both of my accounts. 

This has been happening to me for a few weeks where I either get the illegal password or member error when trying to configure the integration.

**Comment by jjjonesjr33** [comment]
@patti0176 I just received this today in my email from Petlibro. This could be the issue that's been on going this week. I'll keep an eye on it. If and when you're able to log in, please let me know.

![image](https://github.com/user-attachments/assets/05d7398e-89d1-4411-b3dc-7749938e1a0d)

**Comment by jjjonesjr33** [comment]
@patti0176, please let me know if you're still encountering this issue, and feel free to reopen it so we can investigate further.

**Comment by YamenSharaf** [comment]
I'm having the same issue as OP. From the logs:

```
Logger: custom_components.petlibro.config_flow
Source: custom_components/petlibro/config_flow.py:125
integration: PETLIBRO ([documentation](https://github.com/jjjonesjr33/petlibro), [issues](https://github.com/jjjonesjr33/petlibro/issues))
First occurred: 9:57:43 AM (8 occurrences)
Last logged: 2:26:17 PM

Unexpected exception during validation: Login attempt failed: Code: 1102, Message: ILLEGAL_PASSWORD
Unexpected exception during validation: Login attempt failed: Code: 1101, Message: MEMBER_NOT_EXIST
Traceback (most recent call last):
  File "/config/custom_components/petlibro/api.py", line 211, in login
    data = await self.session.request("POST", "/member/auth/login", json={
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<10 lines>...
    })
    ^^
  File "/config/custom_components/petlibro/api.py", line 111, in request
    raise PetLibroAPIError(f"Code: {data.get('code')}, Message: {data.get('msg')}")
custom_components.petlibro.exceptions.PetLibroAPIError: Code: 1102, Message: ILLEGAL_PASSWORD

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/petlibro/config_flow.py", line 125, in _validate_input
    self.token = await api.login(self.email, self.password)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/petlibro/api.py", line 234, in login
    raise PetLibroAPIError(f"Login attempt failed: {e}")
custom_components.petlibro.exceptions.PetLibroAPIError: Login attempt failed: Code: 1102, Message: ILLEGAL_PASSWORD
```

Account is set to Canada/US and I tried two passwords:
- 14 chars only lower +uppercase + number
- 18 chars only lower +uppercase + number
Made sure I logged out of the app

Anything I can try here?

EDIT: After restarting HA. Still can't login but this is the log

```
This error originated from a custom integration.

Logger: custom_components.petlibro.config_flow
Source: custom_components/petlibro/config_flow.py:125
integration: PETLIBRO (documentation, issues)
First occurred: 2:39:13 PM (1 occurrences)
Last logged: 2:39:13 PM

Unexpected exception during validation: Login attempt failed: Code: 1101, Message: MEMBER_NOT_EXIST
Traceback (most recent call last):
  File "/config/custom_components/petlibro/api.py", line 211, in login
    data = await self.session.request("POST", "/member/auth/login", json={
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<10 lines>...
    })
    ^^
  File "/config/custom_components/petlibro/api.py", line 111, in request
    raise PetLibroAPIError(f"Code: {data.get('code')}, Message: {data.get('msg')}")
custom_components.petlibro.exceptions.PetLibroAPIError: Code: 1101, Message: MEMBER_NOT_EXIST

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/petlibro/config_flow.py", line 125, in _validate_input
    self.token = await api.login(self.email, self.password)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/petlibro/api.py", line 234, in login
    raise PetLibroAPIError(f"Login attempt failed: {e}")
custom_components.petlibro.exceptions.PetLibroAPIError: Login attempt failed: Code: 1101, Message: MEMBER_NOT_EXIST
```

**Comment by jjjonesjr33** [comment]
@YamenSharaf make sure you look over the [Account Management](https://github.com/jjjonesjr33/petlibro/wiki/PetLibro-Account-Management) and [PetLibro Password Limitation](https://github.com/jjjonesjr33/petlibro/wiki/PetLibro-Password-Limitation) in the wiki.

From what I’ve noticed, creating an account on the app is completely separate from their web domains. It looks like no matter which region you pick, as long as you create the account through the app, it lets you access the API.

Did you setup your user account via their website or the app?

**Comment by peqoud** [comment]
Maybe something to add in the documentation, that only accounts created via the PETLIRBO app are working. 
The accounts with PETLIBRO LITE are not working.

**Comment by jjjonesjr33** [comment]
@peqoud that was originally talked about in the community post on HA forms. https://community.home-assistant.io/t/petlibro-cloud-integration-non-tuya-wip/759978

I thought I had it in the wiki already. If not I'll check it in a bit and make sure it's added. I know the older devices use Tuya if you have any. You might be able to go that route to add them to HA.
