### ISSUE TITLE
[Region]: Switzerland addition

### ISSUE THREAD

**Issue by andreasfromch** [jjjonesjr33/petlibro#7]
### What happened ?

Hi, 
after adding the integration and entring my credentials I get an "Unexpected error". I'm located in Switzerland therefore not in the US region. Is it possible that that's the problem? I not is there anything I can try?
Thanks for any Help
Andreas

![PETLIBRO](https://github.com/user-attachments/assets/a3c93244-2079-48b4-87de-9b2f300c1ca3)

### Relevant log output

```python
Unexpected error
```

**Comment by jjjonesjr33** [comment]
At this moment, only the US region is available. However if I am able to find the information/api for the other regions I can program them in. 

One thing to try in the meantime would be to create a US account and see about adding the device to it and try logging in via that method.

**Comment by C4-Dimitri** [comment]
To be honest - i have not seen any requirement for creating any specific regioned account. mine is set to Europe/UK and working just fine with US selected. i doubt your issue is related to region.

are you sure your account is set up for the normal Petlibro app, and not the Tuya one?

**Comment by jjjonesjr33** [comment]
@C4-Dimitri you know I forgot about the Tuya app/version. One thing though I would think we could still somehow access that via this with logging in since we are pulling from the api. Unless that is more a local only type setup.

**Comment by andreasfromch** [comment]
Thanks for the hint! I’ve just created a new account with “**US selected**”. Now everything works great. Thanks again!
